export const SET_CONFIGS = "SET_CONFIGS";
export const RESET_CONFIG = "RESET_CONFIG";

export const SET_TEMP_STATE = "SET_TEMP_STATE";
export const SET_TEMP_STATE_REQUEST = "SET_TEMP_STATE_REQUEST";
export const REMOVE_TEMP_STATE_REQUEST = "REMOVE_TEMP_STATE_REQUEST";
